### ISSUE TITLE
Upgrade to new versioned and content APIs

### ISSUE THREAD

**Issue by aafaq-hassan-confiz** [mdesjardins/linkedin-v2#22]
This [Shares API](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/share-api) is being sunset on Feb 28,2023.

This [Posts API](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/posts-api) is a replacement of Shares API.

Will this gem be upgraded to new Posts API? 

If not, then is there any other gem available for new Posts API?

**Comment by mdesjardins** [comment]
Unfortunately I've stopped maintaining this project as I'm no longer working in this space. I'll update the README to let people know. :/
